CREATE TABLE members (
    id VARCHAR(20) PRIMARY KEY,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM members;